spring:
  application:
    name: comment
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    url: jdbc:mysql://192.168.5.137:3306/comment?serverTimezone=UTC
  redis:
    host: 192.168.5.137
    port: 6379
    password: 1234
    lettuce:
      pool:
        min-idle: 1
        max-idle: 10
        max-active: 10
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null  # JSON处理时忽略非空字段
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB

mybatis-plus:
  type-aliases-package: org.comment.entity

logging:
  level:
    org.comment: debug

server:
  port: 8082

springdoc:
  api-docs:
    enabled: true
    path: /doc-api.html
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: on